### ISSUE TITLE
Any other permalink_structure than default is not working in http://degrona.ypcs.fi/wordpress/

### ISSUE THREAD

**Issue by 0is1** [VihreatDeGrona/degrona15#28]
For example 
```
/%year%/%monthnum%/%day%/%postname%/ 
```
that creates this permalink: http://degrona.ypcs.fi/wordpress/2015/01/04/tiedote-tervetuloa-kayttamaan-wordpressia/ (not in use at the moment)

**Comment by ypcs** [comment]
Wontfix (tämä projekti obsolete).
